'use strict';

/**
 * report-format.js
 * Markdown and one-line summary formatters for the governance report.
 *
 * Extracted from governance-report.js so baseline-aware output does not push
 * the report generator past the file length limit. When a baseline is
 * applied (report.baseline.applied), the scan rows show 'N new / M legacy'
 * instead of a flat violation count.
 */

/**
 * Violation cell text for a scan check, baseline-aware.
 *
 * @param {object} check - checks.fileLength or checks.secrets
 * @param {boolean} baselineApplied
 * @returns {string}
 */
function violationCell(check, baselineApplied) {
  if (!baselineApplied) return `${check.violations} violations`;
  return `${check.violations} new / ${check.legacyViolations || 0} legacy violations`;
}

/**
 * Render the full Markdown governance report.
 *
 * @param {object} report - generateReport() output
 * @returns {string}
 */
function formatMarkdown(report) {
  const badge = s => s === 'pass' ? 'PASS' : s === 'skip' ? 'SKIP' : 'FAIL';
  const baselined = Boolean(report.baseline && report.baseline.applied);
  const hookLabel = (id) => {
    const s = report.governance.runtimeHooks[id];
    if (s === 'registered') return 'verified';
    if (s === 'registered_broken') return 'broken';
    if (s === 'not_registered') return 'none';
    return 'n/a';
  };

  const healthDetail = report.checks.installHealth.missing
    ? 'Missing: ' + report.checks.installHealth.missing.join(', ')
    : 'All source files present';

  const lines = [
    '## Code-Warden Governance Report',
    '',
    '| Check | Result | Details |',
    '|-------|--------|---------|',
    `| File length | ${badge(report.checks.fileLength.status)} | ${report.checks.fileLength.filesScanned} files scanned, ${violationCell(report.checks.fileLength, baselined)} |`,
    `| Hardcoded credentials | ${badge(report.checks.secrets.status)} | ${report.checks.secrets.filesScanned} files scanned, ${violationCell(report.checks.secrets, baselined)} |`,
    `| Behavioral tests | ${badge(report.checks.behavioralTests.status)} | ${report.checks.behavioralTests.tests} tests, ${report.checks.behavioralTests.failures} failures |`,
    `| Install health | ${badge(report.checks.installHealth.status)} | ${healthDetail} |`,
    `| Risk policy | ${badge(report.checks.riskPolicy.status)} | ${Object.keys(report.checks.riskPolicy.actions).length} governed actions |`,
    `| Runtime hooks | — | Claude: ${hookLabel('claude')} / Codex: ${hookLabel('codex')} |`,
    '',
    `**Result:** ${report.result === 'pass' ? 'All governed checks passed.' : 'One or more checks failed.'}`,
  ];

  if (baselined) {
    lines.push('', `> Baseline applied (${report.baseline.path}): ` +
      `${report.baseline.legacy.fileLength} legacy file-length and ` +
      `${report.baseline.legacy.secrets} legacy secret finding(s) excluded from the gate.`);
  }

  lines.push('', `> Generated by Code-Warden v${report.version} at ${report.timestamp}`);
  return lines.join('\n');
}

/**
 * Render the one-line summary printed in default mode.
 *
 * @param {object} report - generateReport() output
 * @returns {string}
 */
function formatSummary(report) {
  const c = report.checks;
  const parts = [
    `lint:${c.fileLength.status}`,
    `secrets:${c.secrets.status}`,
    `tests:${c.behavioralTests.status}`,
    `health:${c.installHealth.status}`,
    `risk:${c.riskPolicy.status}`,
  ];
  let line = `[CodeWarden] Governance report: ${report.result.toUpperCase()} (${parts.join(', ')})`;
  if (report.baseline && report.baseline.applied) {
    line += ` [baseline: lint ${c.fileLength.violations} new / ${c.fileLength.legacyViolations || 0} legacy,` +
      ` secrets ${c.secrets.violations} new / ${c.secrets.legacyViolations || 0} legacy]`;
  }
  return line;
}

module.exports = { formatMarkdown, formatSummary, violationCell };
